version: '3'
services:
  qbittorrent:
    container_name: qBittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/mediaserver/data/torrents:/data/torrents/
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - media_network
    restart: unless-stopped

  homarr:
    container_name: Homarr
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /mnt/mediaserver/data/arrs/homarr/configs:/app/data/configs
      - /mnt/mediaserver/data/arrs/homarr/icons:/app/public/icons
      - /mnt/mediaserver/data/arrs/homarr/data:/data
    ports:
      - 80:7575 # Sets 80 to route to 7575 so Homarr opens by default
    networks:
      - media_network
    restart: unless-stopped

  jellyfin:
    container_name: Jellyfin
    image: ghcr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/mediaserver/data/media:/data/media/
    ports:
      - 8096:8096
    networks:
      - media_network
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 9696:9696
    networks:
      - media_network
    restart: unless-stopped

  radarr:
    container_name: Radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/mediaserver/data:/data/
    ports:
      - 7878:7878
    networks:
      - media_network
    restart: unless-stopped

  sonarr:
    container_name: Sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/mediaserver/data:/data
    ports:
      - 8989:8989
    networks:
      - media_network
    restart: unless-stopped

  jellyseerr:
    container_name: Jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/mediaserver/data/arrs/jellyseerr/configs:/app/config
    ports:
      - 5055:5055
    networks:
      - media_network
    restart: unless-stopped

networks:
  media_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1