############################################################################
##  __  __          _ _        _____                                      ##
## |  \/  |        | (_)      / ____|                                     ##
## | \  / | ___  __| |_  __ _| |     ___  _ __ ___  _ __   ___  ___  ___  ##
## | |\/| |/ _ \/ _` | |/ _` | |    / _ \| '_ ` _ \| '_ \ / _ \/ __|/ _ \ ##
## | |  | |  __/ (_| | | (_| | |___| (_) | | | | | | |_) | (_) \__ \  __/ ##
## |_|  |_|\___|\__,_|_|\__,_|\_____\___/|_| |_| |_| .__/ \___/|___/\___| ##
##                                                 | |                    ##
##                                                 |_|                    ##
##                                                                        ##
##       ___        ___           _   _                 ___               ##
##      | _ )_  _  / __| ___ _  _| |_| |_  ___ _ _ _ _ / __|  _ _ _ ___   ##
##      | _ \ || | \__ \/ _ \ || |  _| ' \/ -_) '_| ' \ (_| || | '_/ -_)  ##
##      |___/\_, | |___/\___/\_,_|\__|_||_\___|_| |_||_\___\_,_|_| \___|  ##
##           |__/                                                         ##
############################################################################

version "3":
services:
  Qbittorent:

  Homarr:

  